export const ROUTES = {
  landing: '/',
  signup: '/signup',
  signupChoose: '/signup/choose-user-type',
  signupSignUp: '/signup/sign-up',
  signupSignIn: '/signup/sign-in',
  signupVerification: '/signup/verification-code',
  signupAddExperience: '/signup/add-experience',
  signupEditProfile: '/signup/edit-profile',
  signupEditProfileCompany: '/signup/edit-profile-company',
  app: '/app',
  appHome: '/app/home',
  appJobs: '/app/jobs',
  appJob: (jobId) => `/app/jobs/${jobId}`,
  appNotifications: '/app/notifications',
  appInbox: '/app/inbox',
  appThread: (threadId) => `/app/inbox/${threadId}`,
  appProfile: '/app/profile',
  appSettings: '/app/settings',
};
